name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.IP }}
          port: 2222
          username: Jordi
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /var/www/html/DPL4/
            git reset --hard; git pull
            php artisan view:cache
            php artisan route:cache
            sudo service php8.4-fpm reload
            sudo service php8.4-fpm restart
            npm run build
